//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summarry_tragil_for_test
{
    using System;
    using System.Collections.Generic;
    
    public class CustomerOrder
    {
        public int Id { get; set; }
        public int Customer_Id { get; set; }
        public int Price { get; set; }
        public string Date { get; set; }
        public string Customer_Name { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
